FROM ubuntu:25.04

RUN apt -y update \
	&& apt -y upgrade \
	&& apt install -y nginx

RUN apt install -y wget\
	&& apt install -y gpg

RUN echo "code code/add-microsoft-repo boolean true" | debconf-set-selections\
	&&wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg\
	&& install -D -o root -g root -m 644 packages.microsoft.gpg /etc/apt/keyrings/packages.microsoft.gpg\
	&& echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" |tee /etc/apt/sources.list.d/vscode.list > /dev/null

RUN apt install -y apt-transport-https\
	&& apt update -y\
	&& apt install -y code

CMD ["code","serve-web","--without-connection-token","--host","0.0.0.0"]


